query AlbumsPage($pagination: PaginationInput!) {
    albums(pagination: $pagination) {
      edges {
        node {
          id
          name
          albumArtists {
            id
            name
          }
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
}