query AlbumsPage($pagination: PaginationInput!) {
  albums(pagination: $pagination) {
    edges {
      node {
        ...Album
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
