query GenrePage($genreId: GenreID!, $pagination: PaginationInput!) {
  genre(id: $genreId) {
    id
    name
    albums(pagination: $pagination) {
      nodes {
        ...AlbumCard
      }

      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
