[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { default-features = false, features = [
    "graphiql",
    "time",
], version = "7.0.16" }
anyhow = "1.0.98"
async-graphql-axum = "7.0.16"
axum = "0.8.4"
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
env_logger = "0.11.8"
log = "0.4.27"
pomsky-macro = "0.11.0"
rand = "0.9.1"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread", "fs"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.4", features = ["cors", "fs"] }
walkdir = "2.5.0"
indicatif = "0.17.11"
symphonia = { version = "0.5.4", features = ["all"] }
image = { version = "0.25.6", default-features = false, features = [
    "jpeg",
    "png",
    "webp",
] }
rayon = "1.10.0"
jiff = { version = "0.2.13", features = ["serde"] }
