[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { default-features = false, features = [
    "graphiql",
    "time",
], version = "7.0.2" }
anyhow = "1.0.79"
async-graphql-axum = "7.0.2"
axum = "0.7.4"
clap = { version = "4.5.1", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
env_logger = "0.11.2"
log = "0.4.20"
once_cell = "1.19.0"
pomsky-macro = "0.11.0"
rand = "0.8.5"
regex = "1.10.3"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
time = { version = "0.3.34", features = ["local-offset", "std", "serde"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "fs"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.1", features = ["cors", "fs"] }
walkdir = "2.4.0"
indicatif = "0.17.8"
symphonia = { version = "0.5.3", features = ["all"] }
