[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-graphql = "4.0.16"
async-graphql-rocket = "4.0.16"
clap = { version = "4.0.23", features = ["derive"] }
color-thief = "0.2.2"
dirs = "4.0.0"
image = "0.24.5"
once_cell = "1.16.0"
pomsky = "0.7.0"
pomsky-macro = "0.7.0"
rand = "0.8.5"
rayon = "1.5.3"
regex = "1.7.0"
rocket = "0.5.0-rc.2"
rocket_seek_stream = "0.2.5"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
time = { version = "0.3.17", features = ["local-offset", "std", "serde"] }
walkdir = "2.3.2"
