[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0.13"
async-graphql-rocket = "4.0.13"
clap = { version = "3.2.22", features = ["derive"] }
lazy_static = "1.4.0"
rayon = "1.5.3"
regex = "1.6.0"
rocket = "0.5.0-rc.2"
rocket_seek_stream = "0.2.5"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
walkdir = "2.3.2"
