[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
juniper = "0.15.9"
juniper_rocket = "0.8.0"
lazy_static = "1.4.0"
rayon = "1.5.1"
regex = "1.5.5"
rocket = "0.5.0-rc.1"
serde = { version= "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
walkdir = "2.3.2"
