[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { default-features = false, features = [
    "graphiql",
    "time",
], version = "7.0.11" }
anyhow = "1.0.89"
async-graphql-axum = "7.0.11"
axum = "0.7.7"
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
env_logger = "0.11.5"
log = "0.4.22"
pomsky-macro = "0.11.0"
rand = "0.8.5"
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "fs"] }
tower = { version = "0.5.1", features = ["util"] }
tower-http = { version = "0.6.1", features = ["cors", "fs"] }
walkdir = "2.5.0"
indicatif = "0.17.8"
symphonia = { version = "0.5.4", features = ["all"] }
image = { version = "0.25.2", default-features = false, features = [
    "jpeg",
    "png",
    "webp",
] }
rayon = "1.10.0"
jiff = { version = "0.1.13", features = ["serde"] }
