[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-graphql = "5.0.6"
async-graphql-axum = "5.0.6"
axum = "0.6.11"
clap = { version = "4.1.11", features = ["derive"] }
color-thief = "0.2.2"
dirs = "5.0.0"
image = { version = "0.24.5", default-features = false, features = ["jpeg", "png"] }
mime_guess = "2.0.4"
once_cell = "1.17.1"
pomsky-macro = "0.9.0"
rand = "0.8.5"
rayon = "1.7.0"
regex = "1.7.2"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
time = { version = "0.3.20", features = ["local-offset", "std", "serde"] }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { version = "0.7.7", features = ["io"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.4.0", features = ["cors", "fs"] }
walkdir = "2.3.3"
