[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { default-features = false, features = [
    "graphiql",
], version = "5.0.10" }
anyhow = "1.0.71"
async-graphql-axum = "5.0.10"
axum = "0.6.18"
clap = { version = "4.3.11", features = ["derive"] }
colored = "2.0.4"
dirs = "5.0.1"
env_logger = "0.10.0"
log = "0.4.20"
once_cell = "1.18.0"
pomsky-macro = "0.10.0"
rand = "0.8.5"
rayon = "1.7.0"
regex = "1.9.1"
serde = { version = "1.0.170", features = ["derive"] }
serde_json = "1.0.100"
time = { version = "0.3.23", features = ["local-offset", "std", "serde"] }
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread", "fs"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.4.1", features = ["cors", "fs"] }
walkdir = "2.3.3"
indicatif = "0.17.6"
