[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "3.0.37"
async-graphql-rocket = "3.0.37"
clap = { version = "3.1.8", features = ["derive"] }
lazy_static = "1.4.0"
rayon = "1.5.1"
regex = "1.5.5"
rocket = "0.5.0-rc.1"
rocket_seek_stream = { git = "https://github.com/StappsWorld/rocket_seek_stream.git", rev = "502467db7d307256ebd208b2865457935c21d024" }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tantivy = "0.17.0"
walkdir = "2.3.2"

[features]
