[package]
name = "hify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-graphql = "5.0.6"
async-graphql-rocket = "5.0.6"
clap = { version = "4.1.8", features = ["derive"] }
color-thief = "0.2.2"
dirs = "4.0.0"
image = "0.24.5"
once_cell = "1.17.1"
pomsky = "0.9.0"
pomsky-macro = "0.9.0"
rand = "0.8.5"
rayon = "1.7.0"
regex = "1.7.1"
rocket = "0.5.0-rc.2"
rocket_seek_stream = "0.2.5"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
time = { version = "0.3.20", features = ["local-offset", "std", "serde"] }
walkdir = "2.3.2"
