query PlaylistPage($playlistId: String!, $tracksPagination: PaginationInput!) {
    playlist(playlistId: $playlistId) {
        id
        name
        createdAt
        lastUpdatedAt
        entriesCount
        entries(pagination: $tracksPagination) {
            nodes {
                ...PlaylistEntry
            }

            pageInfo {
                endCursor
                hasNextPage
            }
        }
    }
}