export const ROUTES = {
	home: '/',
	albums: '/albums',
	artists: '/artists',
	genres: '/genres',
	playlists: '/playlists',
	album: (id: string) => `/album/${id}`,
	artist: (id: string) => `/artist/${id}`,
	genre: (id: string) => `/genre/${id}`,
	playlist: (id: string) => `/playlist/${id}`,
	history: '/history',
	nowPlaying: '/playing',
	search: '/search',
	searchTerms: (terms: string) => `/search/${encodeURIComponent(terms)}`,
	devTools: '/dev',
}
