query SearchPage($input: String!, $limit: Int!) {
  search(input: $input, limit: $limit) {
    tracks {
      ...AudioTrack
    }
    albums {
      id
      name
      albumArtists {
        id
        name
      }
    }
    artists {
      ...ArtistCard
    }
  }
}
