query SearchPage($input: String!, $limit: Int!, $albumYearStrategy: AlbumYearStrategy!) {
  search(input: $input, limit: $limit) {
    tracks {
      ...AudioTrack
    }
    albums {
      id
      name
      albumArtists {
        id
        name
      }
    }
    artists {
      id
      name
    }
  }
}