query ArtistAlbums($artistId: ArtistID!, $pagination: PaginationInput!) {
  artist(id: $artistId) {
    albums(pagination: $pagination) {
      nodes {
        ...AlbumCard
      }

      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
