query ArtistTrackParticipations($artistId: ArtistID!, $pagination: PaginationInput!) {
  artist(id: $artistId) {
    trackParticipations(pagination: $pagination) {
      nodes {
        ...AudioTrack
      }

      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
