query ArtistPage($artistId: String!, $pagination: PaginationInput!) {
  artist(id: $artistId) {
    name
    albumParticipations(pagination: $pagination) {
      nodes {
        ...AlbumCard
      }

      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
