query ArtistPage($artistId: String!, $pagination: PaginationInput!, $strategy: AlbumYearStrategy!) {
  artist(id: $artistId) {
    name
    albumParticipations(pagination: $pagination) {
      nodes {
        id
        name
        hasArtImage
        genres {
          id
          name
        }
        year(strategy: $strategy)
        albumArtists {
          id
          name
        }
      }

      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
