query ArtistPage($artistId: String!, $pagination: PaginationInput!) {
  artist(id: $artistId) {
    name
    albumParticipations(pagination: $pagination) {
      nodes {
        id
        name
        hasArtImage
        genres {
          id
          name
        }
        year
        albumArtists {
          id
          name
        }
      }

      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
