fragment AudioTrack on Track {
  id
  metadata {
    format
    duration
    size
    tags {
      title
      artists {
        id
        name
      }
      album {
        ...AlbumCard

        year

        art {
          dominantColor {
            r
            g
            b
          }
        }
      }
      disc
      trackNo
      rating
      genres {
        id
        name
      }
      date {
        year
        month
        day
      }
    }
  }
}
