query HomePage($input: FeedParams!) {
  generateFeed(input: $input) {
    lastListenedTo {
      ...AudioTrack
    }

    periodicallyPopularTracks {
      ...AudioTrack
    }

    # popularTracks {
    #   ...AudioTrack
    # }

    # popularAlbums {
    #   ...AlbumCard
    # }

    # popularArtists {
    #   ...ArtistCard
    # }

    randomGreatAlbums {
      ...AlbumCard
    }

    randomGreatArtists {
      ...ArtistCard
    }
  }
}
