query HomePage {
  generateFeed(input: {}) {
    lastListenedTo {
      ...AudioTrack
    }

    popularTracks {
      ...AudioTrack
    }

    popularAlbums {
      ...AlbumCard
    }

    popularArtists {
      ...ArtistCard
    }

    randomGreatAlbums {
      ...AlbumCard
    }

    randomGreatArtists {
      ...ArtistCard
    }
  }
}
