query HomePage($input: FeedParams!) {
  generateFeed(input: $input) {
    lastListenedTo {
      ...AudioTrack
    }

    periodicallyPopularTracks {
      ...AudioTrack
    }

    mostRecentAlbums {
      ...AlbumCard
    }

    # popularTracks {
    #   ...AudioTrack
    # }

    # popularAlbums {
    #   ...AlbumCard
    # }

    # popularArtists {
    #   ...ArtistCard
    # }

    # randomGreatAlbums {
    #   ...AlbumCard
    # }

    # randomGreatArtists {
    #   ...ArtistCard
    # }
  }
}
