query AlbumPage($albumId: String!) {
  album(id: $albumId) {
    name
    albumArtists {
      id
      name
    }
    tracks {
      id
      metadata {
        tags {
          trackNo
          title
          artists {
            id
            name
          }
        }
      }
    }
  }
}