query AlbumPage($albumId: String!, $albumYearStrategy: AlbumYearStrategy!) {
  album(id: $albumId) {
    ...Album
    year(strategy: $albumYearStrategy)
    genres {
      id
      name
    }
    tracks {
      ...AudioTrack
    }
  }
}
