query PlaylistsPage($pagination: PaginationInput!) {
    playlists(pagination: $pagination) {
        nodes {
            id
            name
            createdAt
            lastUpdatedAt
            tracksCount
        }

        pageInfo {
            endCursor
            hasNextPage
        }
    }
}