query ArtistsPage($pagination: PaginationInput!) {
    albumsArtists(pagination: $pagination) {
      edges {
        node {
          id
          name
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
}