query ArtistsPage($pagination: PaginationInput!) {
  albumsArtists(pagination: $pagination) {
    id # for cache
    nodes {
      ...ArtistCard
    }

    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
