use std::hash::{BuildHasher, Hasher, RandomState};

/// PCG-XSH-RR (PCG32) Random Number Generator
/// A fast, statistically excellent random number generator
///
/// Generated by Claude Opus 4.5, edited by hand
pub struct Rng {
    state: u64,
    increment: u64,
}

impl Rng {
    /// Default increment value (must be odd)
    pub const DEFAULT_INCREMENT: u64 = 1_442_695_040_888_963_407;

    // Create a PCG32 generator with a random seed
    pub fn new() -> Self {
        Self::with_seed(
            RandomState::default().build_hasher().finish(),
            RandomState::default().build_hasher().finish(),
        )
    }

    /// Creates a new PCG32 generator
    pub fn with_seed(seed: u64, inc: u64) -> Self {
        let mut rng = Self {
            state: 0,
            increment: inc,
        };

        // Advance state once and mix in the seed
        rng.next_u32();
        rng.state = rng.state.wrapping_add(seed);
        rng.next_u32();
        rng
    }

    /// Generates the next random u32 value
    pub fn next_u32(&mut self) -> u32 {
        let old_state = self.state;

        // Advance internal state using LCG
        self.state = old_state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(self.increment);

        // Calculate output function (XSH-RR)
        #[allow(clippy::as_conversions, clippy::cast_possible_truncation)]
        let xorshifted = (((old_state >> 18) ^ old_state) >> 27) as u32;

        #[allow(clippy::as_conversions)]
        let rot = (old_state >> 59) as u32;

        xorshifted.rotate_right(rot)
    }

    pub fn next_u64(&mut self) -> u64 {
        let high = u64::from(self.next_u32());
        let low = u64::from(self.next_u32());
        (high << 32) | low
    }
}

/// Shuffles a vector in place using the Fisher-Yates algorithm with a PCG32 generator.
/// The shuffle is deterministic - the same seed and increment will always produce the same order.
///
/// # Arguments
/// * `vec` - The vector to shuffle in place
/// * `pcg` - A mutable reference to a PCG32 random number generator
///
/// # Example
/// ```
/// let mut rng = Rng::new();
/// let mut data = vec![1, 2, 3, 4, 5];
/// shuffle(&mut data, &mut rng);
/// ```
///
/// Written by Claude Opus 4.5, edited by hand
pub fn deterministic_shuffle<T>(vec: &mut [T], rng: &mut Rng) {
    let len = vec.len();
    if len <= 1 {
        return;
    }

    // Fisher-Yates shuffle (modern algorithm)
    for i in (1..len).rev() {
        // Generate a random index from 0 to i (inclusive)
        let j = usize::try_from(rng.next_u32()).unwrap() % (i + 1);
        vec.swap(i, j);
    }
}
