
query Index($fingerprint: String!) {
    index(fingerprint: $fingerprint) {
        creationTime
        tracks {
            id
            path
            metadata {
              format
            }
        }
    }
}