query AlbumTracks($albumId: String!) {
  album(id: $albumId) {
    tracks {
      id
      metadata {
        tags {
          trackNo
          title
          artists {
            id
            name
          }
        }
      }
    }
  }
}